import fs from 'node:fs';
import assert from 'node:assert/strict';

const html = fs.readFileSync(new URL('../manual-tool/index.html', import.meta.url), 'utf8');

function extractFunctionBody(name) {
  const start = html.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `${name} should exist`);
  const open = html.indexOf('{', start);
  let depth = 0;
  for (let i = open; i < html.length; i++) {
    if (html[i] === '{') depth++;
    if (html[i] === '}') depth--;
    if (depth === 0) return html.slice(open + 1, i);
  }
  assert.fail(`${name} should have a complete body`);
}

assert.match(html, /id="addCustomColorBtn"/, 'custom color add button should exist');
assert.match(html, /id="customColorModal"/, 'custom color modal should exist');
assert.match(html, /id="customColorInput"/, 'color input should exist');
assert.match(html, /id="customColorHexInput"/, 'hex input should exist');
assert.match(html, /manualToolCustomColors/, 'custom colors should be persisted in localStorage');
assert.match(html, /function normalizeHexColor/, 'hex colors should be normalized before use');
assert.match(html, /function renderCustomColorButtons/, 'saved custom colors should render into the palette');
assert.match(html, /function selectColorButton/, 'dynamic color buttons should share the existing selection behavior');
assert.match(html, /function calculateFittedCanvasSize/, 'canvas fit size should be reusable after viewport changes');
assert.match(html, /function resizeCanvasToViewport/, 'canvas should resize when the viewport grows or shrinks');
assert.match(html, /window\.addEventListener\('resize', handleWindowResize\)/, 'window resize should trigger canvas refit');
assert.match(html, /imageAutoFitEnabled = false/, 'manual background resizing should disable automatic viewport fitting');
assert.match(html, /const intrinsicWidth = img\.naturalWidth \|\| img\.width/, 'pasted images should preserve their source pixel width');
assert.match(html, /const intrinsicHeight = img\.naturalHeight \|\| img\.height/, 'pasted images should preserve their source pixel height');
assert.match(html, /setCanvasSize\(intrinsicWidth, intrinsicHeight\)/, 'canvas backing resolution should use original image pixels');
const setupCanvasBody = html.match(/function setupCanvasWithImage\(img, isFreshLoad = true\) \{([\s\S]*?)\n    window\.addEventListener\('resize', handleWindowResize\)/);
assert.ok(setupCanvasBody, 'setupCanvasWithImage should be inspectable');
assert.doesNotMatch(setupCanvasBody[1], /calculateFittedCanvasSize\(img\)/, 'initial paste should not downsample canvas to the viewport');
assert.match(setupCanvasBody[1], /fitViewportToWorkspace\(false\)/, 'initial paste should fit visually without changing canvas pixels');
const resizeCanvasBody = html.match(/function resizeCanvasToViewport\(\) \{([\s\S]*?)\n    let resizeTimer/);
assert.ok(resizeCanvasBody, 'resizeCanvasToViewport should be inspectable');
assert.doesNotMatch(resizeCanvasBody[1], /setCanvasSize\(/, 'window resize should not change canvas backing resolution');
assert.doesNotMatch(resizeCanvasBody[1], /scaleAbsoluteCanvasItems\(/, 'window resize should not rescale annotations');
assert.match(resizeCanvasBody[1], /fitViewportToWorkspace\(false\)/, 'window resize should only refit the viewport transform');
assert.match(html, /function fitViewportToWorkspace\(allowUpscale = true\)/, 'viewport fitting should support non-upscaling initial fit');
assert.match(html, /if \(!allowUpscale\) nextScale = Math\.min\(1, nextScale\)/, 'initial viewport fit should avoid scaling small screenshots above 100%');
assert.match(html, /const CREATION_TOOLS = \['focus-rect', 'focus-circle', 'badge'\]/, 'creation tools should stay active for repeated placement');
assert.match(html, /function isFocusCreationTool/, 'focus creation tools should share creation-mode focus editing checks');
assert.match(html, /function startActiveFocusEditIfHit/, 'active focus created in creation mode should be editable before leaving that mode');
assert.match(html, /if \(startActiveFocusEditIfHit\(pos\)\) return;[\s\S]*?selectedFocusArea = null; selectedElement = null; multiSel = \[\];/, 'clicking the active focus should edit it, while clicking elsewhere should clear it before new drawing');
assert.doesNotMatch(html, /if \(CREATION_TOOLS\.includes\(currentTool\)\) {\s*selectedFocusArea = null;\s*}/, 'created focus shapes should stay active in creation mode after mouseup');
assert.match(html, /if \(justDrewFocus && !CREATION_TOOLS\.includes\(currentTool\)\)/, 'only non-creation focus drawing should force select mode');
assert.match(html, /let copiedComponents = \[\]/, 'selected components should have an internal clipboard');
assert.match(html, /let componentClipboardFresh = false/, 'internal component clipboard should track whether the last copy came from the editor');
assert.match(html, /function copySelectedComponents/, 'selected components should be copyable');
assert.match(html, /function pasteCopiedComponents/, 'copied components should be pasteable');
assert.match(html, /saveHistoryState\(\); drawCanvas\(\); updateSelectedActionArea\(\);[\s\S]*?붙여넣었습니다/, 'pasted components should be saved into undo history');
assert.match(html, /e\.key\.toLowerCase\(\) === 'c'[\s\S]*?copySelectedComponents/, 'Ctrl+C should copy selected components');
const keydownBody = html.match(/window\.addEventListener\('keydown', \(e\) => \{([\s\S]*?)\n    function selectToolByShortcut/);
assert.ok(keydownBody, 'global keydown handler should be inspectable');
assert.match(keydownBody[1], /e\.key\.toLowerCase\(\) === 'c'[\s\S]*?getSelectionList\(\)\.length > 0[\s\S]*?copySelectedComponents\(\)[\s\S]*?isProjectPageKeyboardContext\(\)[\s\S]*?copySelectedPages\(\)/, 'Ctrl+C should prioritize selected canvas components even if the page rail still has keyboard focus');
assert.match(keydownBody[1], /e\.key\.toLowerCase\(\) === 'v'[\s\S]*?pageClipboardFresh[\s\S]*?!shouldPasteFreshCopiedComponents\(\)[\s\S]*?pasteCopiedPages\(\)/, 'Ctrl+V page paste should only run for a fresh internal page copy');
assert.match(keydownBody[1], /e\.key\.toLowerCase\(\) === 'd'[\s\S]*?getSelectionList\(\)\.length > 0[\s\S]*?duplicateSelectedComponents\(\)[\s\S]*?isProjectPageKeyboardContext\(\)[\s\S]*?duplicateSelectedPages\(\)/, 'Ctrl+D should prioritize selected canvas components even if the page rail still has keyboard focus');
assert.match(keydownBody[1], /e\.key === 'Delete' \|\| e\.key === 'Backspace'[\s\S]*?executeDeleteSelected\(\)[\s\S]*?isProjectPageKeyboardContext\(\)[\s\S]*?deleteSelectedPages\(\)/, 'Delete should prioritize selected canvas components even if the page rail still has keyboard focus');
assert.doesNotMatch(keydownBody[1], /pasteCopiedComponents/, 'Ctrl+V should not let a stale internal component clipboard override OS clipboard image paste from keydown');
assert.match(html, /function clipboardHasImagePayload/, 'paste handling should detect OS clipboard images before component fallback');
assert.match(html, /function shouldPasteFreshCopiedComponents/, 'paste handling should distinguish fresh editor copies from stale internal clipboard data');
assert.match(html, /let pageClipboardFresh = false/, 'internal page clipboard should track whether the last page copy is fresh');
assert.match(html, /function isPasteEditableTarget/, 'paste handling should only ignore text-editing targets, not toolbar buttons');
assert.match(extractFunctionBody('handlePaste'), /if \(isPasteEditableTarget\(e\.target\)\) return;/, 'image paste should still run when focus remains on a toolbar button after adding a page');
assert.doesNotMatch(extractFunctionBody('handlePaste'), /isInteractiveViewportTarget\(e\.target\)/, 'button focus should not block image paste on a newly added page');
assert.match(extractFunctionBody('isProjectPageKeyboardContext'), /projectPageList/, 'page keyboard context should be limited to the page list');
assert.doesNotMatch(extractFunctionBody('isProjectPageKeyboardContext'), /projectPageRail\.contains/, 'page rail toolbar buttons should not hijack Ctrl+V image paste');
assert.match(extractFunctionBody('copySelectedComponents'), /componentClipboardFresh = true/, 'copying selected components should mark the internal clipboard as fresh');
assert.match(extractFunctionBody('copySelectedComponents'), /pageClipboardFresh = false/, 'copying components should clear fresh page clipboard priority');
assert.match(extractFunctionBody('copySelectedPages'), /pageClipboardFresh = true/, 'copying pages should mark the internal page clipboard as fresh');
assert.match(extractFunctionBody('copySelectedPages'), /componentClipboardFresh = false/, 'copying pages should clear fresh component clipboard priority');
assert.match(extractFunctionBody('handlePaste'), /const hasImagePayload = clipboardHasImagePayload\(e\)/, 'paste handling should inspect the current OS clipboard payload');
assert.match(extractFunctionBody('handlePaste'), /if \(shouldPasteFreshCopiedComponents\(\) && pasteCopiedComponents\(\)\) \{[\s\S]*?e\.preventDefault\(\);[\s\S]*?return;[\s\S]*?\}/, 'fresh editor copies should paste components before stale OS image payloads');
assert.match(extractFunctionBody('handlePaste'), /if \(!hasImagePayload && pasteCopiedComponents\(\)\) \{[\s\S]*?e\.preventDefault\(\);[\s\S]*?return;[\s\S]*?\}/, 'component paste should be a fallback only when the OS clipboard has no image payload');
assert.match(extractFunctionBody('handlePaste'), /if \(hasImagePayload\) \{[\s\S]*?componentClipboardFresh = false;[\s\S]*?pageClipboardFresh = false;[\s\S]*?\}/, 'an OS image paste should stale internal editor clipboards');
assert.doesNotMatch(extractFunctionBody('pasteCopiedComponents'), /componentClipboardFresh = false/, 'component paste should keep the editor clipboard fresh for repeated paste');
assert.match(extractFunctionBody('handleViewportWindowBlur'), /componentClipboardFresh = false/, 'leaving the editor should stale the editor clipboard so later OS screenshots can paste as images');
assert.match(extractFunctionBody('handleViewportWindowBlur'), /pageClipboardFresh = false/, 'leaving the editor should stale page copy priority so later OS screenshots can paste as images');
assert.doesNotMatch(extractFunctionBody('copySelectedComponents'), /currentTool\s*!==\s*'select'/, 'selected components should be copyable even while a creation tool remains active');
assert.doesNotMatch(extractFunctionBody('pasteCopiedComponents'), /currentTool\s*!==\s*'select'/, 'copied components should paste even while a creation tool remains active');
assert.doesNotMatch(extractFunctionBody('duplicateSelectedComponents'), /currentTool\s*!==\s*'select'/, 'selected components should duplicate even while a creation tool remains active');
assert.doesNotMatch(extractFunctionBody('nudgeSelected'), /currentTool\s*!==\s*'select'/, 'arrow-key nudging should use selection state instead of select mode');
assert.match(html, /function flushPendingNudgeHistory/, 'arrow-key nudges should be flushable before undo-sensitive commands');
assert.match(extractFunctionBody('handleUndo'), /flushPendingNudgeHistory\(\)/, 'undo should first commit pending arrow-key movement');
assert.match(extractFunctionBody('handleRedo'), /flushPendingNudgeHistory\(\)/, 'redo should first commit pending arrow-key movement');
assert.match(extractFunctionBody('executeDeleteSelected'), /flushPendingNudgeHistory\(\)/, 'delete should not race against deferred nudge history');
assert.match(extractFunctionBody('pasteCopiedComponents'), /flushPendingNudgeHistory\(\)/, 'component paste should not race against deferred nudge history');
assert.match(html, /function isNearHandle/, 'resize hit testing should target handles, not the whole border');
const focusHandleBody = html.match(/function getFocusHandleAt\(pos, f\) \{([\s\S]*?)\n    function getCropHandleAt/);
assert.ok(focusHandleBody, 'focus handle hit testing should be inspectable');
assert.doesNotMatch(focusHandleBody[1], /Math\.abs\(pos\.y - f\.y\) < size && inX/, 'top focus border should not all become a resize handle');
assert.doesNotMatch(focusHandleBody[1], /Math\.abs\(pos\.x - f\.x\) < size && inY/, 'left focus border should not all become a resize handle');
assert.match(html, /id="badgeTypePanel"[^>]*hidden/, 'badge type options should be hidden initially');
assert.match(html, /function updateToolSpecificPanels/, 'tool-specific option panels should be updated on tool changes');
assert.match(html, /badgeTypePanel\.classList\.toggle\('hidden', currentTool !== 'badge'\)/, 'badge type options should only show in badge mode');
assert.match(html, /id="selectedTextEditArea"/, 'selected badge and text elements should expose a text edit area');
assert.match(html, /id="selectedTextColorInput"/, 'selected badge and text elements should expose text color editing');
assert.doesNotMatch(html, /id="selectedTextColorInput"[^>]*type="color"/, 'selected text color editing should not use the native color picker');
assert.match(html, /id="selectedTextColorPalette"/, 'selected text color editing should use an in-panel palette');
assert.match(html, /function toggleSelectedTextColorPalette/, 'selected text color palette should be toggled inside the app');
assert.match(html, /function setSelectedTextColorDraft/, 'selected text color palette should update the draft color without closing');
assert.match(html, /function applySelectedTextColor/, 'selected text color palette should immediately apply color to the selected element');
assert.match(html, /applySelectedTextColor\(btn\.getAttribute\('data-color'\)\)/, 'clicking a text color option should update the selected element immediately');
assert.match(html, /const toolDefaults = \{/, 'editor styles should have tool-level defaults');
assert.match(html, /badge: \{ fillColor: '#FF4747', textColor: '#FFFFFF', badgeStyle: 'number', badgeScale: 1, borderColor: '#FFFFFF', borderOpacity: 0 \}/, 'badge tool should keep fill, text color, label, size, and border defaults');
assert.match(html, /id="textStylePanel"/, 'text style controls should live in a tool/selection style panel');
assert.match(html, /toolDefaults\.badge\.textColor = normalized/, 'badge mode color changes should update future badge defaults');
assert.match(html, /textColor: toolDefaults\.badge\.textColor/, 'new badges should copy the badge tool text color');
assert.match(html, /textColor: toolDefaults\.text\.textColor/, 'new text bubbles should copy the text tool text color');
assert.match(html, /id="badgeBorderStylePanel"[^>]*hidden/, 'badge border controls should live in their own panel');
assert.match(html, /id="badgeBorderColorSwatch"/, 'badge border color should use a swatch control');
assert.match(html, /id="badgeBorderColorInput"[^>]*class="w-20 min-w-0/, 'badge border color hex input should match existing color inputs');
assert.match(html, /id="badgeBorderColorPalette" class="grid grid-cols-6 gap-1.5"/, 'badge border palette should match existing palette layout');
assert.match(html, /id="badgeBorderTransparencyValue">100%<\/span>/, 'hidden default badge border should show 100 percent transparency');
assert.match(html, /id="badgeBorderTransparencyRange"[^>]*value="100"/, 'badge border transparency should default to fully transparent');
assert.match(html, /function hexToRgba/, 'badge border opacity should render through RGBA color conversion');
assert.match(html, /function getBadgeBorderOpacity/, 'badge border opacity should be normalized');
assert.match(html, /function getBadgeBorderTransparency/, 'badge border transparency should be derived from alpha opacity');
assert.match(html, /function transparencyToBorderOpacity/, 'badge border transparency should convert to render opacity');
assert.match(html, /function updateBadgeBorderStylePanel/, 'badge border panel should update by current tool and selection');
assert.match(html, /function applyBadgeBorderColor/, 'badge border color should apply through a style controller');
assert.match(html, /function applyBadgeBorderTransparency/, 'badge border transparency should apply through a style controller');
assert.match(html, /toolDefaults\.badge\.borderColor = normalized/, 'badge mode border color changes should update future badge defaults');
assert.match(html, /toolDefaults\.badge\.borderOpacity = transparencyToBorderOpacity\(transparency\)/, 'badge mode transparency changes should update future badge opacity defaults');
assert.match(html, /item\.borderOpacity = transparencyToBorderOpacity\(transparency\)/, 'selected badge transparency changes should update per-badge opacity');
assert.match(html, /applyBadgeBorderTransparency\(Number\(badgeBorderTransparencyRange\.value\) \/ 100\)/, 'range input should pass transparency, not opacity');
assert.match(html, /borderColor: toolDefaults\.badge\.borderColor/, 'new badges should copy badge border color default');
assert.match(html, /borderOpacity: toolDefaults\.badge\.borderOpacity/, 'new badges should copy badge border opacity default');
assert.match(html, /ctx\.strokeStyle = hexToRgba\(el\.borderColor \|\| toolDefaults\.badge\.borderColor, getBadgeBorderOpacity\(el\)\)/, 'badge drawing should use per-badge border color and opacity');
assert.doesNotMatch(html, /테두리 & 뱃지 색상/, 'generic color panel label should be removed');
assert.match(html, /id="objectStylePanel"[^>]*hidden/, 'fill and stroke colors should live in a mode-specific style panel');
assert.match(html, /id="objectStylePanelTitle"/, 'mode-specific style panel should have a dynamic title');
assert.match(html, /id="objectColorSwatch"/, 'object color panel should use the same swatch control as text color');
assert.match(html, /id="objectColorInput"[^>]*class="w-20 min-w-0/, 'object color hex input should match text color input sizing');
assert.match(html, /id="colorPalette" class="grid grid-cols-6 gap-1.5"/, 'object color palette should use the same grid layout as text color');
assert.match(html, /class="color-picker-btn w-6 h-6 rounded-full border border-slate-200 bg-\[#FFFFFF\]" data-color="#FFFFFF"/, 'object color palette should include the same white swatch as text color');
assert.doesNotMatch(html, /color-picker-btn[^"]*w-7 h-7/, 'object custom color swatches should use the same size as text color swatches');
assert.doesNotMatch(html, /class="color-picker-btn[^"]*ring-\[/, 'object color swatches should not use a different selected-state UI from text color swatches');
assert.match(html, /function updateObjectStylePanel/, 'object style panel should update by current tool and selection');
assert.match(html, /function applyObjectFillColor/, 'fill and stroke color choices should apply through the style controller');
assert.match(html, /toolDefaults\.badge\.fillColor = normalized/, 'badge mode fill color changes should update future badge defaults');
assert.match(html, /color: toolDefaults\.badge\.fillColor/, 'new badges should copy the badge tool fill color');
assert.match(html, /function getSingleEditableTextElement/, 'text editing should target one selected badge or text element');
assert.match(html, /function applySelectedTextEdit/, 'selected text edits should be applied explicitly');
assert.match(html, /el\.textColor \|\| '#ffffff'/, 'badge and text drawing should support per-element text colors');
assert.match(html, /if \(el\.manualText\) \{ count\+\+; return; \}/, 'manually edited badge labels should not be overwritten and should consume sequence order');
assert.match(html, /let viewportScale = 1/, 'workspace should track a separate viewport zoom scale');
assert.match(html, /function applyViewportTransform/, 'viewport transform should be centralized');
assert.match(html, /function zoomViewportAt/, 'wheel zoom should preserve the pointer anchor');
assert.match(html, /id="resetViewportBtn"/, 'viewport navigation should expose a reset-to-origin button');
assert.match(html, /id="viewportZoomToolbar"/, 'viewport navigation controls should be grouped in a toolbar');
assert.match(html, /id="zoomOutBtn"/, 'viewport toolbar should expose zoom out');
assert.match(html, /id="zoomInBtn"/, 'viewport toolbar should expose zoom in');
assert.match(html, /id="fitViewportBtn"/, 'viewport toolbar should expose fit-to-screen');
assert.match(html, /<main class="[^"]*overflow-hidden/, 'editor workspace should not use native scrolling while viewport zoom handles wheel input');
assert.doesNotMatch(html, /<main class="[^"]*overflow-auto/, 'editor workspace should not scroll vertically while wheel zooming');
assert.doesNotMatch(html, /id="actualSizeViewportBtn"/, 'viewport toolbar should not expose a duplicate actual-size view');
assert.match(html, /id="zoomPercentLabel"/, 'viewport toolbar should show the current zoom percent');
assert.match(html, /const resetViewportBtn = document\.getElementById\('resetViewportBtn'\)/, 'reset viewport button should be bound');
assert.match(html, /const zoomOutBtn = document\.getElementById\('zoomOutBtn'\)/, 'zoom out button should be bound');
assert.match(html, /const zoomInBtn = document\.getElementById\('zoomInBtn'\)/, 'zoom in button should be bound');
assert.match(html, /const fitViewportBtn = document\.getElementById\('fitViewportBtn'\)/, 'fit viewport button should be bound');
assert.doesNotMatch(html, /actualSizeViewportBtn/, 'actual-size button wiring should be removed');
assert.match(html, /const zoomPercentLabel = document\.getElementById\('zoomPercentLabel'\)/, 'zoom percent label should be bound');
assert.match(html, /function handleViewportWheel/, 'workspace wheel events should drive viewport zoom');
assert.match(html, /function shouldHandleViewportWheel/, 'wheel zoom should be filtered before changing zoom');
assert.match(html, /function isInteractiveViewportTarget/, 'viewport wheel and context-menu handlers should recognize editable controls');
assert.match(html, /function handleViewportPanStart/, 'right-button drag should start viewport panning');
assert.match(html, /function handleViewportPanMove/, 'right-button drag should move the viewport');
assert.match(html, /function handleViewportMousePanMove/, 'mouse events should back up right-button panning if pointer events are cancelled by the browser');
assert.match(html, /function handleViewportPointerCancel/, 'pointer cancellation should be handled without dropping active right-button pans');
assert.match(html, /function shouldCancelViewportPanFromMove/, 'pan move cancellation should be based on the active pan button, not a raw zero-buttons check');
assert.match(html, /function finishViewportPan/, 'right-button drag should end viewport panning cleanly');
assert.match(html, /function updateViewportZoomLabel/, 'viewport zoom percent should update after zoom changes');
assert.match(html, /function zoomViewportByStep/, 'viewport toolbar should reuse step zoom behavior');
assert.match(html, /function setViewportScaleAtCenter/, 'toolbar zoom should anchor at the workspace center');
assert.match(html, /function fitViewportToWorkspace/, 'viewport should support fitting the whole canvas into the workspace');
assert.match(html, /function updateViewportResetButton/, 'reset-to-origin button visibility should follow image state');
assert.match(html, /function updateViewportToolbar/, 'viewport toolbar visibility and disabled state should be centralized');
assert.match(html, /zoomOutBtn\.addEventListener\('click'[\s\S]*?zoomViewportByStep\(1\)/, 'zoom out button should zoom out one step');
assert.match(html, /zoomInBtn\.addEventListener\('click'[\s\S]*?zoomViewportByStep\(-1\)/, 'zoom in button should zoom in one step');
assert.match(html, /fitViewportBtn\.addEventListener\('click', fitViewportToWorkspace\)/, 'fit button should fit the canvas to the workspace');
assert.match(html, /resetViewportBtn\.addEventListener\('click', resetViewportTransform\)/, 'reset-to-origin button should reset viewport transform');
assert.match(html, /e\.key === '0'[\s\S]*?resetViewportTransform\(\)/, 'Ctrl+0 should reset viewport transform');
assert.match(html, /e\.key === '=' \|\| e\.key === '\+'/, 'Ctrl+plus should zoom in');
assert.match(html, /e\.key === '-'[\s\S]*?zoomViewportByStep\(1\)/, 'Ctrl+minus should zoom out');
assert.match(html, /let isSpacePanActive = false/, 'space-drag panning should track spacebar state');
assert.match(html, /e\.button === 1 \|\| \(e\.button === 0 && isSpacePanActive\)/, 'viewport panning should also support middle drag and space-left drag');
assert.match(html, /e\.code === 'Space'[\s\S]*?isSpacePanActive = true/, 'holding Space should enable panning');
assert.match(html, /function clearSpacePanState/, 'space-pan should have one cleanup path shared by keyup and blur');
assert.match(html, /window\.addEventListener\('keyup'[\s\S]*?clearSpacePanState\(\)/, 'releasing Space should stop space-pan mode');
assert.match(html, /function handleViewportWindowBlur/, 'window blur should clear stuck viewport input state');
assert.match(extractFunctionBody('handleViewportWindowBlur'), /clearSpacePanState\(\);[\s\S]*?finishViewportPan\(\)/, 'window blur should stop space-pan and active panning together');
assert.match(html, /canvasContainer\.addEventListener\('wheel', handleViewportWheel, \{ passive: false \}\)/, 'wheel zoom should be scoped to the canvas instead of the whole workspace');
assert.doesNotMatch(html, /workspace\.addEventListener\('wheel', handleViewportWheel/, 'workspace-level wheel zoom should not accidentally catch unrelated scroll events');
assert.match(html, /const VIEWPORT_WHEEL_AFTER_PAN_IGNORE_MS = \d+/, 'stray wheel events immediately after panning should be ignored');
assert.match(html, /Date\.now\(\) - lastViewportPanEndedAt < VIEWPORT_WHEEL_AFTER_PAN_IGNORE_MS/, 'wheel zoom should ignore residual wheel events right after panning');
assert.match(html, /Math\.abs\(e\.deltaY\) < 1/, 'wheel zoom should ignore zero vertical wheel delta');
assert.match(html, /Math\.abs\(e\.deltaX\) > Math\.abs\(e\.deltaY\)/, 'horizontal wheel gestures should not be treated as zoom');
assert.match(html, /if \(!shouldHandleViewportWheel\(e\)\) return;/, 'wheel handler should return before preventing default when a wheel is unrelated to zooming');
assert.match(html, /function shouldSuppressHorizontalViewportWheel/, 'horizontal wheel suppression should be centralized');
assert.match(html, /Math\.abs\(e\.deltaX\) >= 1/, 'horizontal wheel suppression should detect real horizontal deltas');
assert.match(html, /Math\.abs\(e\.deltaX\) >= Math\.abs\(e\.deltaY\)/, 'horizontal wheel suppression should ignore diagonal vertical zoom gestures');
assert.match(html, /function suppressHorizontalViewportWheel/, 'workspace horizontal wheel events should have a suppress-only handler');
assert.match(html, /workspace\.addEventListener\('wheel', suppressHorizontalViewportWheel, \{ passive: false, capture: true \}\)/, 'horizontal wheel suppression should run before workspace scrolling');
assert.match(html, /if \(shouldSuppressHorizontalViewportWheel\(e\)\) \{[\s\S]*?e\.preventDefault\(\);[\s\S]*?e\.stopPropagation\(\);[\s\S]*?return;[\s\S]*?\}/, 'canvas wheel handler should block horizontal wheel default scrolling without zooming');
assert.match(html, /if \(!shouldSuppressHorizontalViewportWheel\(e\)\) return;[\s\S]*?e\.preventDefault\(\);[\s\S]*?e\.stopPropagation\(\);/, 'workspace suppress handler should prevent and stop horizontal wheel events');
assert.match(html, /workspace\.addEventListener\('pointerdown', handleViewportPanStart, true\)/, 'right-click panning should use pointer events before canvas editing handlers');
assert.match(html, /document\.addEventListener\('contextmenu', suppressViewportContextMenu, true\)/, 'context menu should be suppressed at capture phase while viewport panning is available');
assert.match(html, /workspace\.contains\(e\.target\)/, 'context menu suppression should stay scoped to the editing workspace');
assert.match(html, /window\.addEventListener\('pointermove', handleViewportPanMove\)/, 'panning should continue if the pointer leaves the canvas');
assert.match(html, /window\.addEventListener\('pointerup', finishViewportPan\)/, 'panning should stop on global pointerup');
assert.match(html, /window\.addEventListener\('pointercancel', handleViewportPointerCancel\)/, 'right-button pointer cancellation should be handled without immediately dropping the pan');
assert.match(html, /window\.addEventListener\('mousemove', handleViewportMousePanMove, true\)/, 'mousemove should keep right-button panning alive when pointermove is unreliable');
assert.match(html, /window\.addEventListener\('mouseup', finishViewportPanFromMouse, true\)/, 'mouseup should end panning even if pointerup was swallowed');
assert.match(html, /window\.addEventListener\('blur', handleViewportWindowBlur\)/, 'panning and space-pan should stop when the browser window loses focus');
assert.match(html, /workspace\.setPointerCapture\(e\.pointerId\)/, 'viewport panning should capture the active pointer');
assert.match(html, /workspace\.releasePointerCapture\(panPointerId\)/, 'viewport panning should release pointer capture when done');
assert.match(html, /if \(isPanningViewport\) \{[\s\S]*?e\.preventDefault\(\);[\s\S]*?e\.stopPropagation\(\);[\s\S]*?return;[\s\S]*?\}/, 'wheel input during panning should be swallowed without ending the pan');
assert.doesNotMatch(extractFunctionBody('handleViewportPanMove'), /e\.buttons === 0[\s\S]*?finishViewportPan/, 'right-button pointermove should not drop panning just because buttons is transiently zero');
assert.match(extractFunctionBody('handleViewportPointerCancel'), /if \(panPointerButton === 2 \|\| panPointerButton === 1\) return;/, 'right and middle button pans should survive browser pointercancel events');
assert.match(html, /canvas\.addEventListener\('mousedown'[\s\S]*?if \(e\.button !== 0 \|\| isSpacePanActive\) return;/, 'canvas editing should ignore right, middle, and space-pan mouse actions');
const viewportWheelBody = html.match(/function shouldHandleViewportWheel\(e\) \{([\s\S]*?)\n    function handleViewportWheel/);
assert.ok(viewportWheelBody, 'wheel zoom guard should be inspectable');
assert.doesNotMatch(viewportWheelBody[1], /currentTool/, 'wheel zoom should not be limited to a specific editing mode');
assert.match(viewportWheelBody[1], /isInteractiveViewportTarget\(e\.target\)[\s\S]*?return false/, 'wheel zoom should not hijack inputs, textareas, buttons, or contenteditable controls');
assert.match(extractFunctionBody('shouldSuppressHorizontalViewportWheel'), /isInteractiveViewportTarget\(e\.target\)[\s\S]*?return false/, 'horizontal wheel suppression should not hijack editable controls');
const viewportPanBody = html.match(/function handleViewportPanStart\(e\) \{([\s\S]*?)\n    function handleViewportPanMove/);
assert.ok(viewportPanBody, 'viewport pan start guard should be inspectable');
assert.doesNotMatch(viewportPanBody[1], /currentTool/, 'viewport panning should not be limited to a specific editing mode');
assert.match(html, /if \(!bgImage \|\| canvasContainer\.classList\.contains\('hidden'\)\) return false;/, 'wheel zoom should work in every editing mode when an image is loaded');
assert.match(html, /if \(e\.code === 'Space' && bgImage\)/, 'space panning should work in every editing mode');
assert.match(html, /if \(!shouldPan \|\| !bgImage \|\| canvasContainer\.classList\.contains\('hidden'\)\) return;/, 'right and middle panning should work in every editing mode');
assert.match(extractFunctionBody('handleWorkspaceEmptyMouseDown'), /if \(isSpacePanActive \|\| isPanningViewport\) return;/, 'space or active viewport panning on the pasteboard should not clear selection');
assert.match(extractFunctionBody('handleCanvasEditMouseMove'), /if \(isPanningViewport\) return;/, 'viewport panning should not mutate active edit gestures such as unfinished lines');
assert.match(extractFunctionBody('finishCanvasEditInteraction'), /if \(e\?\.type === 'mouseup' && e\.button !== 0\) return;/, 'right and middle mouseup should not finalize left-button edit gestures');
assert.match(extractFunctionBody('suppressViewportContextMenu'), /isInteractiveViewportTarget\(e\.target\)[\s\S]*?return;/, 'viewport context menu suppression should not block form controls');
assert.match(extractFunctionBody('suppressViewportContextMenu'), /if \(bgImage && isViewportContext\)/, 'viewport context menu suppression should not depend on select mode');
assert.match(html, /\(e\.clientX - bgInitialClientX\) \/ viewportScale/, 'background resize drag distance should stay correct while the viewport is zoomed');
assert.match(html, /const BADGE_BASE_RADIUS = 14/, 'badge drawing should have a reusable base radius');
assert.match(html, /const BADGE_MIN_SCALE = 0\.6/, 'badge resizing should have a minimum scale');
assert.match(html, /const BADGE_MAX_SCALE = 3/, 'badge resizing should have a maximum scale');
assert.match(html, /function getBadgeScale/, 'badge elements should normalize their scale');
assert.match(html, /function getBadgeRadius/, 'badge drawing should use a reusable scaled radius');
assert.match(html, /function getBadgeBounds/, 'badge selection should expose bounds for handles and snapping');
assert.match(html, /function getBadgeHandleAt/, 'selected badges should expose resize handles');
assert.match(html, /function resizeBadgeFromPoint/, 'badge resizing should be pointer driven');
assert.match(html, /let isPlacingBadge = false/, 'badge placement should track mouse-down drag placement');
assert.match(html, /let placingBadge = null/, 'badge placement should keep the pending badge until mouseup');
assert.match(html, /isPlacingBadge = true/, 'badge mousedown should start placement instead of saving immediately');
assert.match(html, /if \(isPlacingBadge && placingBadge\)/, 'badge mousemove should update the pending badge');
assert.match(html, /function finishBadgePlacement/, 'badge placement should finalize through a reusable mouseup handler');
assert.match(html, /window\.addEventListener\('mouseup', finishCanvasEditInteraction\)/, 'badge placement should finalize even if the pointer leaves the canvas');
assert.match(html, /scale: toolDefaults\.badge\.badgeScale/, 'new badges should copy the tool-level size default');
assert.match(html, /let isResizingBadge = false/, 'badge resizing should have explicit interaction state');
assert.match(html, /if \(selectedElement && selectedElement\.type === 'badge'\)/, 'badge resize handles should be checked before dragging selection');
assert.match(html, /if \(isResizingBadge && selectedElement && selectedElement\.type === 'badge'\)/, 'badge mousemove should resize the selected badge');
assert.match(html, /if \(isResizingFocus && selectedFocusArea\) \{[\s\S]*?resizeSelectedFocusFromPoint\(pos, e\);[\s\S]*?return;[\s\S]*?\}/, 'active focus resizing should work outside select mode');
assert.match(html, /if \(isDragging\) \{[\s\S]*?moveCurrentSelectionByPointer\(pos, e\);[\s\S]*?return;[\s\S]*?\}/, 'active focus moving should work outside select mode');
assert.match(html, /function getItemBounds/, 'snap logic should use shared item bounds');
assert.match(html, /function getBoundsForItems/, 'snap logic should support moving grouped selections');
assert.match(html, /function getSnapAnchors/, 'snap logic should compare edges, centers, and corners');
assert.match(html, /function getSnapTargets/, 'snap logic should collect canvas and component targets');
assert.match(html, /function snapAnchorsToTargets/, 'snap matching should support custom source anchors, not only bounding boxes');
assert.match(html, /function getShiftedSelectionSnapAnchors/, 'moving selections should expose shifted source anchors');
assert.match(extractFunctionBody('getShiftedSelectionSnapAnchors'), /item\.type === 'line'[\s\S]*?point\.x \+ dx[\s\S]*?point\.y \+ dy/, 'moving selected lines should snap their endpoints, not only the line bounds');
assert.match(html, /function snapBoundsToTargets/, 'moving and placing should adjust to nearby snap targets');
assert.match(html, /const SNAP_RELEASE_THRESHOLD_PX = \d+/, 'snap should have a larger release threshold so aligned objects can detach intentionally');
assert.match(html, /let selectionDragState = null/, 'selection dragging should track the original unsnapped bounds for the whole gesture');
assert.match(html, /function beginSelectionDrag/, 'selection dragging should initialize one gesture-level drag state');
assert.match(html, /function getSnapReleaseThreshold/, 'snap release threshold should be computed in canvas coordinates');
assert.match(html, /function shouldReleaseSnappedAxis/, 'snapped axes should detach only after intentional movement away from the target');
assert.match(html, /function finishSelectionDrag/, 'selection drag state should be cleared when the interaction ends');
assert.doesNotMatch(extractFunctionBody('moveCurrentSelectionByPointer'), /dragStartX\s*=\s*pos\.x;\s*dragStartY\s*=\s*pos\.y;/, 'selection movement should not reset drag origin every frame because that makes snapped objects sticky');
assert.match(extractFunctionBody('moveCurrentSelectionByPointer'), /const rawDx = pos\.x - selectionDragState\.startX/, 'selection movement should use total pointer distance from the drag origin');
assert.match(extractFunctionBody('moveCurrentSelectionByPointer'), /restoreSelectionDragItems\(selection\)/, 'selection movement should restore original item bounds before applying the current snapped delta');
assert.match(extractFunctionBody('restoreSelectionDragItems'), /setObjectBounds\(item, originalBounds\)/, 'selection drag restoration should reset each item before applying the current gesture delta');
assert.match(extractFunctionBody('getSnappedMoveDelta'), /snapAnchorsToTargets\(getShiftedSelectionSnapAnchors\(items, targetBounds, dx, dy\), items\)/, 'selection move snap should use source anchors from the moved objects');
assert.match(html, /function snapFocusResizeToTargets/, 'focus resize should use snap targets like standard editors');
assert.match(extractFunctionBody('resizeSelectedFocusFromPoint'), /snapFocusResizeToTargets\(selectedFocusArea, e\)/, 'focus resizing should snap the active resize edge');
assert.match(extractFunctionBody('handleCanvasEditMouseMove'), /resizeSelectedFocusFromPoint\(pos, e\)/, 'focus resize should receive the pointer event so Shift can bypass snap');
assert.match(extractFunctionBody('snapFocusDraftToTargets'), /focus\.type === 'circle'[\s\S]*?Math\.max\(Math\.abs\(nextW\), Math\.abs\(nextH\)\)/, 'circle focus drafts should snap while preserving a circular bounding box');
assert.doesNotMatch(extractFunctionBody('handleCanvasEditMouseMove'), /selectedFocusArea\.type === 'circle'[\s\S]*?activeSnapGuides = \[\];/, 'circle focus drawing should not explicitly disable snap guides');
assert.match(html, /function drawSnapGuides/, 'snap alignments should be visible while editing');
assert.match(html, /activeSnapGuides = snapResult\.guides/, 'active snap guides should be updated from snap results');
assert.match(html, /const SNAP_THRESHOLD_PX = 8/, 'snap threshold should be defined in screen pixels');
assert.match(html, /canvas\.width \/ rect\.width/, 'snap threshold should account for viewport zoom');
assert.match(html, /item\.type === 'line'[\s\S]*?item\.points\.forEach/, 'line endpoints should contribute snap anchors');
assert.match(html, /function shouldBypassSnap\(e\)/, 'snap bypass should be centralized');
assert.match(html, /return e\?\.shiftKey === true/, 'holding Shift should bypass snap behavior');
assert.match(html, /function applySnapUnlessBypassed\(e, snapAction\)/, 'snap application and Shift bypass should share one helper');
assert.match(html, /if \(shouldBypassSnap\(e\)\) \{[\s\S]*?activeSnapGuides = \[\];[\s\S]*?return false;[\s\S]*?\}/, 'snap bypass helper should clear guides and report that snapping was skipped');
assert.doesNotMatch(html, /applySnapUnlessBypassed\(e, \(\) => applySnapToBadgePlacement\(newBadge\)\)/, 'initial badge creation should not snap on mousedown');
assert.doesNotMatch(html, /applySnapUnlessBypassed\(e, \(\) => applySnapToBadgePlacement\(placingBadge\)\)/, 'drag-sizing a new badge should not snap while the size is being chosen');
assert.match(html, /applySnapUnlessBypassed\(e, \(\) => applySnapToBadgeResize\(selectedElement\)\)/, 'holding Shift should disable snap while resizing badges');
assert.match(
  extractFunctionBody('moveCurrentSelectionByPointer'),
  /const snappedDelta = shouldBypassSnap\(e\) \? \{ dx: rawDx, dy: rawDy \} : getSnappedMoveDelta\(selection, rawDx, rawDy, selectionDragState\)/,
  'holding Shift should disable snap while moving selected components'
);
assert.match(
  extractFunctionBody('moveCurrentSelectionByPointer'),
  /if \(shouldBypassSnap\(e\)\) \{[\s\S]*?selectionDragState\.snapX = null;[\s\S]*?selectionDragState\.snapY = null;[\s\S]*?activeSnapGuides = \[\];[\s\S]*?\}/,
  'holding Shift should clear snap state and visible guides during movement'
);
assert.match(html, /points\[points\.length - 1\] = shouldBypassSnap\(e\) \? orthogonalPos : snapPointToTargets\(orthogonalPos, \[drawingLineInstance\]\)/, 'holding Shift should disable snap while moving line endpoints');
assert.match(html, /function snapFocusDraftToTargets\(focus, e\)/, 'focus draft snapping should receive the pointer event');
assert.match(html, /if \(shouldBypassSnap\(e\)\) \{[\s\S]*?activeSnapGuides = \[\];[\s\S]*?return;[\s\S]*?\}/, 'holding Shift should disable snap while drawing focus rectangles');
assert.match(html, /if \(e\.key === 'Shift' && activeSnapGuides\.length\)/, 'pressing Shift should immediately clear visible snap guides');

const redoBody = html.match(/function handleRedo\(\) \{([\s\S]*?)\n    function applySnapshot/);
assert.ok(redoBody, 'redo handler should be inspectable');
assert.match(redoBody[1], /history\.push\(next\)/, 'redo should push the redone snapshot into undo history');
assert.doesNotMatch(redoBody[1], /history\.push\(current\)/, 'redo should not push the pre-redo snapshot as the new undo baseline');

assert.match(html, /function createHistorySnapshot/, 'history snapshots should be created through a reusable helper');
const historySnapshotBody = html.match(/function createHistorySnapshot\(\) \{([\s\S]*?)\n    function saveHistoryState/);
assert.ok(historySnapshotBody, 'history snapshot helper should be inspectable');
['focusAreas', 'elements', 'selectedObjectIds', 'canvasWidth', 'canvasHeight', 'bgImage', 'originalBgImage', 'cropArea', 'dimOpacity', 'currentScalePreset', 'autoScaleEnabled', 'watermarkEnabled', 'watermarkOpacity', 'watermarkSize', 'watermarkPos'].forEach(key => {
  assert.match(historySnapshotBody[1], new RegExp(`${key}:`), `history snapshots should include ${key}`);
});
const applySnapshotBody = html.match(/function applySnapshot\(state\) \{([\s\S]*?)[\r\n]+    if \(undoBtn\)/);
assert.ok(applySnapshotBody, 'snapshot restore should be inspectable');
assert.match(applySnapshotBody[1], /syncDocumentVisibility\(\)/, 'snapshot restore should sync dropzone and canvas visibility');
assert.match(applySnapshotBody[1], /syncRenderControlsFromState\(\)/, 'snapshot restore should refresh render-affecting controls');
assert.match(html, /function getSelectionIdsForSnapshot/, 'history snapshots should identify the selected objects by stable ids');
assert.match(html, /function restoreSelectionFromSnapshot/, 'undo and redo should restore selection when the objects still exist');
assert.match(applySnapshotBody[1], /restoreSelectionFromSnapshot\(state\)/, 'snapshot restore should restore selected objects after rehydrating document objects');
assert.match(html, /function clearTransientInteractionState/, 'snapshot restore should have one cleanup path for pointer-only interaction state');
assert.match(
  extractFunctionBody('clearTransientInteractionState'),
  /isDragging = false;[\s\S]*?isResizingFocus = false;[\s\S]*?isResizingBadge = false;[\s\S]*?isDrawingFocus = false;[\s\S]*?isDrawingRedaction = false;[\s\S]*?isEditingLinePoint = false;[\s\S]*?isRotatingSelection = false/,
  'transient cleanup should stop all active edit gestures'
);
assert.match(
  extractFunctionBody('clearTransientInteractionState'),
  /finishSelectionDrag\(\);[\s\S]*?activeSnapGuides = \[\];/,
  'transient cleanup should release gesture-level snap state and visible guides'
);
assert.match(applySnapshotBody[1], /clearTransientInteractionState\(\)/, 'undo and redo should not keep stale drag, resize, snap, or rotation state');
assert.match(extractFunctionBody('setupCanvasWithImage'), /clearTransientInteractionState\(\)/, 'loading a new image should reset active pointer interactions');

const clearCanvasBody = html.match(/clearCanvasBtn\.addEventListener\('click', \(\) => \{([\s\S]*?)\n      \}\);/);
assert.ok(clearCanvasBody, 'clear canvas handler should be inspectable');
assert.doesNotMatch(clearCanvasBody[1], /history = \[\]; redoStack = \[\];/, 'clear canvas should not erase undo history');
assert.match(clearCanvasBody[1], /saveHistoryState\(\)/, 'clear canvas should save a blank undoable snapshot');
const revertImageBody = html.match(/revertImageBtn\.addEventListener\('click', \(\) => \{([\s\S]*?)\n      \}\);/);
assert.ok(revertImageBody, 'revert image handler should be inspectable');
assert.doesNotMatch(revertImageBody[1], /setupCanvasWithImage\(originalBgImage, true\)/, 'revert image should not reset history as a fresh load');
assert.match(revertImageBody[1], /saveHistoryState\(\)/, 'revert image should be undoable');

assert.match(html, /function shouldReplaceCurrentImage/, 'image replacement should be gated through a reusable confirmation helper');
assert.match(html, /if \(!shouldReplaceCurrentImage\('클립보드'\)\) return;/, 'pasting an image over existing work should ask before replacing it');
assert.match(html, /if \(!shouldReplaceCurrentImage\('파일'\)\) return;/, 'loading a file over existing work should ask before replacing it');
assert.match(html, /if \(!shouldReplaceCurrentImage\('드래그 앤 드롭'\)\) return;/, 'dropping a file over existing work should ask before replacing it');

const finishLineBody = html.match(/function finishDrawingLine\(\) \{([\s\S]*?)\n    function handleFileSelect/);
assert.ok(finishLineBody, 'line finalization should be inspectable');
assert.match(finishLineBody[1], /if \(drawingLineInstance\.points\.length < 2\)/, 'one-point lines should be removed instead of saved');
assert.match(finishLineBody[1], /elements = elements\.filter\(el => el !== drawingLineInstance\)/, 'invalid line finalization should remove the pending line object');

const focusHitBody = html.match(/function hitFocusObject\(f, x, y\) \{([\s\S]*?)\n    function findFocusAreaAt/);
assert.ok(focusHitBody, 'focus hit testing should be inspectable');
assert.match(focusHitBody[1], /f\.type === 'circle'/, 'circle focus hit testing should branch by shape type');
assert.match(focusHitBody[1], /normalizedX \* normalizedX \+ normalizedY \* normalizedY <= 1/, 'circle focus hit testing should use ellipse math');

assert.match(html, /function distanceToSegment/, 'line hit testing should use point-to-segment distance');
const elementHitBody = html.match(/function hitElementObject\(el, x, y\) \{([\s\S]*?)\n    function findObjectAt/);
assert.ok(elementHitBody, 'element hit testing should be inspectable');
assert.match(elementHitBody[1], /distanceToSegment\(x, y, el\.points\[i - 1\], el\.points\[i\]\)/, 'line hit testing should check every visible segment');

assert.match(html, /function finishCanvasEditInteraction/, 'canvas edit interactions should share a global finalizer');
assert.match(html, /window\.addEventListener\('mousemove', handleCanvasEditMouseMove\)/, 'canvas editing should keep moving when the pointer leaves the canvas');
assert.match(html, /window\.addEventListener\('mouseup', finishCanvasEditInteraction\)/, 'canvas editing should end on global mouseup');
assert.match(html, /if \(!marqueeMoved && marqueeRect\) \{[\s\S]*?clearSelection\(\);/, 'empty canvas click should deselect instead of selecting the background');
assert.doesNotMatch(html, /selectedElement = 'background'; selectedFocusArea = null; multiSel = \[\];/, 'empty canvas click should no longer select the background implicitly');

const deleteBody = html.match(/function executeDeleteSelected\(\) \{([\s\S]*?)\n    function getSingleEditableTextElement/);
assert.ok(deleteBody, 'delete command should be inspectable');
assert.match(deleteBody[1], /return false;/, 'delete command should return false when nothing was deleted');
assert.match(deleteBody[1], /return true;/, 'delete command should return true after deleting');
assert.match(html, /if \(e\.key === 'Delete' \|\| e\.key === 'Backspace'\) \{[\s\S]*?if \(executeDeleteSelected\(\)\) e\.preventDefault\(\);[\s\S]*?return;[\s\S]*?\}/, 'delete and backspace should prevent browser defaults only when an editor delete ran');

assert.match(html, /if \(\(e\.ctrlKey \|\| e\.metaKey\) && e\.shiftKey && e\.key\.toLowerCase\(\) === 'z'\) \{ e\.preventDefault\(\); handleRedo\(\); return; \}/, 'Ctrl+Shift+Z should redo instead of undo');
assert.match(html, /function cancelActiveInteraction/, 'Escape should route through a central cancel command');
assert.match(html, /if \(e\.key === 'Escape'\) \{[\s\S]*?if \(cancelActiveInteraction\(\)\) e\.preventDefault\(\);[\s\S]*?return;[\s\S]*?\}/, 'Escape should cancel active editor state or clear selection');

assert.match(html, /const VIEWPORT_MIN_SCALE = 0\.05/, 'fit-to-screen should allow very large images to fit into the workspace');
assert.match(html, /function handleWorkspaceEmptyMouseDown/, 'workspace empty clicks should be handled explicitly');
assert.match(html, /workspace\.addEventListener\('mousedown', handleWorkspaceEmptyMouseDown\)/, 'clicking the pasteboard should clear selection');
assert.doesNotMatch(extractFunctionBody('handleWorkspaceEmptyMouseDown'), /currentTool\s*!==\s*'select'/, 'clicking the pasteboard should clear selection even while a creation tool remains active');

assert.match(html, /function indexToAlphaLabel/, 'badge alpha labels should support values past Z');
assert.match(html, /while \(remaining > 0\)/, 'alpha labels should use spreadsheet-style rollover');
const reindexBody = html.match(/function reindexBadges\(\) \{([\s\S]*?)\n    function drawHandles/);
assert.ok(reindexBody, 'badge reindexing should be inspectable');
assert.match(reindexBody[1], /if \(el\.manualText\) \{ count\+\+; return; \}/, 'manual badge labels should consume their sequence slot to avoid duplicate following labels');
assert.match(reindexBody[1], /indexToAlphaLabel\(count, false\)/, 'lowercase alpha badges should use rollover labels');
assert.match(reindexBody[1], /indexToAlphaLabel\(count, true\)/, 'uppercase alpha badges should use rollover labels');

assert.match(html, /function withCleanOutputRender/, 'export and clipboard should render through a clean output state');
assert.match(html, /currentTool = 'select'/, 'clean output render should hide crop overlays and transient editor UI');
assert.match(extractFunctionBody('withCleanOutputRender'), /finally \{[\s\S]*?restoreOutputRenderState\(previousState\);[\s\S]*?\}/, 'clean output render should always restore editor state');
assert.match(html, /withCleanOutputRender\(\(\) => canvas\.toDataURL\('image\/png'\)\)/, 'download should export a clean render');
assert.match(html, /withCleanOutputRender\(\(\) => new Promise/, 'clipboard copy should export a clean render through async cleanup');
assert.match(html, /if \(!blob\) \{ reject\(new Error\('clipboard blob creation failed'\)\); return; \}/, 'clipboard copy should guard against null blobs');
assert.match(html, /if \(!navigator\.clipboard \|\| typeof ClipboardItem === 'undefined'\)/, 'clipboard copy should feature-detect ClipboardItem support');
assert.match(html, /let isRenderingCleanOutput = false/, 'clean export should have an explicit render-mode flag');
assert.match(extractFunctionBody('withCleanOutputRender'), /isRenderingCleanOutput = true;[\s\S]*?finally \{[\s\S]*?isRenderingCleanOutput = previousState\.isRenderingCleanOutput/, 'clean export should temporarily suppress editing overlays and then restore the flag');
assert.match(extractFunctionBody('drawCanvas'), /if \(!isRenderingCleanOutput\) \{[\s\S]*?drawSnapGuides\(\);[\s\S]*?drawImageFrameGuide\(\);[\s\S]*?\}/, 'clean export should not include snap guides or the original image-frame guide');
assert.match(extractFunctionBody('drawCanvas'), /tempCtx\.fillRect\(imageFrame\.x, imageFrame\.y, imageFrame\.w, imageFrame\.h\)/, 'dim overlay should apply only to the original screenshot frame, not expanded canvas margins');

assert.doesNotMatch(html, /id="layersPanel"/, 'manual annotation workflow should not expose an overbuilt layers panel');
assert.doesNotMatch(html, /id="layerList"/, 'manual annotation workflow should not expose a layer list');
assert.match(html, /function ensureObjectIdentity/, 'legacy focus and element records should be normalized into document objects');
assert.match(html, /function normalizeDocumentZIndexes/, 'document objects should share one z-index stack across tool types');
assert.match(html, /function getDocumentObjects/, 'document object model should expose all visible editor objects through one ordered API');
assert.match(html, /zIndex: item\.zIndex/, 'document object records should expose normalized layer order');
assert.match(html, /function addEditorObject/, 'new editor objects should enter through one layer-aware insertion path');
assert.match(html, /item\.zIndex = getNextZIndex\(\)/, 'new editor objects should be placed on top of the layer stack by default');
assert.doesNotMatch(html, /function updateLayersPanel/, 'layer panel rendering should be removed from the manual-focused workflow');
assert.match(html, /function selectObjectRecord/, 'layers panel should select objects through a shared selection controller');
assert.match(html, /function toggleSelectedObjectLock/, 'selected objects should support lock toggling');
assert.match(html, /function toggleSelectedObjectVisibility/, 'selected objects should support visibility toggling');
assert.match(html, /id="lockSelectedBtn"/, 'selected action UI should expose locking because there is no layer panel');
assert.match(html, /id="hideSelectedBtn"/, 'selected action UI should expose hiding because there is no layer panel');
assert.match(html, /id="showHiddenBtn"/, 'visibility controls should include a way to recover hidden objects without a layer panel');
assert.match(html, /lockSelectedBtn\.addEventListener\('click', toggleSelectedObjectLock\)/, 'selected lock button should be wired');
assert.match(html, /hideSelectedBtn\.addEventListener\('click', toggleSelectedObjectVisibility\)/, 'selected hide button should be wired');
assert.match(html, /showHiddenBtn\.addEventListener\('click', showHiddenObjects\)/, 'show hidden button should be wired');
assert.match(html, /function showHiddenObjects/, 'hidden objects should be recoverable from the main editing controls');
assert.match(html, /function isObjectLocked/, 'locked objects should be centrally guarded');
assert.match(html, /function isObjectVisible/, 'hidden objects should be centrally guarded');
assert.match(html, /if \(!isObjectVisible\(f\)\) return;/, 'hidden focus objects should be skipped during rendering');
assert.match(html, /if \(isObjectLocked\(clicked\)\) \{[\s\S]*?showToast\('잠긴 요소입니다\. 선택한 뒤 잠금을 해제하세요/, 'canvas hit testing should not point users to a removed layer panel');
assert.doesNotMatch(html, /id="arrangePanel"/, 'arrange panel should stay out until snap UX proves it is needed');
assert.doesNotMatch(html, /function moveSelectionLayer/, 'z-order buttons should be removed from the manual-focused UI');
assert.match(html, /getDocumentObjects\(\)\.forEach\(record => \{[\s\S]*?drawFocusObject\(record\.item\)[\s\S]*?drawElementObject\(record\.item\)/, 'canvas rendering should follow the shared document object order');
assert.match(html, /const clicked = findObjectAt\(pos\.x, pos\.y\)/, 'canvas hit testing should use shared layer order');
assert.doesNotMatch(html, /function alignSelection/, 'alignment buttons should be deferred in favor of better snap behavior');
assert.doesNotMatch(html, /function distributeSelection/, 'distribution buttons should be deferred in favor of better snap behavior');
assert.doesNotMatch(html, /id="geometryPanel"/, 'numeric geometry panel should be removed from the first-pass manual workflow');
assert.match(html, /function rotateSelectionBy/, 'selected objects should support keyboard or button rotation');
assert.match(html, /rotation: normalizeRotation/, 'history and project snapshots should persist object rotation');
assert.match(html, /id="saveProjectBtn"/, 'editable project export should be available once pages are project-backed');
assert.match(html, /id="loadProjectInput"/, 'editable project import should be available once pages are project-backed');
assert.match(html, /id="projectPageRail"/, 'multi-page projects should expose a slide-style page rail');
assert.match(html, /id="projectPageList"/, 'page rail should have a dedicated page list');
assert.match(html, /id="addProjectPageBtn"/, 'page rail should expose new-page creation');
assert.match(html, /id="duplicateProjectPageBtn"/, 'page rail should expose page duplication');
assert.match(html, /id="deleteProjectPageBtn"/, 'page rail should expose multi-page deletion');
assert.match(html, /id="collapseProjectPageRailBtn"/, 'page rail should expose a collapse control');
assert.match(html, /id="expandProjectPageRailBtn"[^>]*hidden/, 'collapsed page rail should leave a visible restore tab');
assert.match(html, /id="projectPageRailResizeHandle"/, 'page rail should expose a drag resize handle');
assert.match(html, /const PROJECT_PAGE_RAIL_WIDTH_KEY = 'manualToolProjectPageRailWidth'/, 'page rail width should persist in localStorage');
assert.match(html, /const PROJECT_PAGE_RAIL_COLLAPSED_KEY = 'manualToolProjectPageRailCollapsed'/, 'page rail collapsed state should persist in localStorage');
assert.match(html, /let projectPageRailWidth = PROJECT_PAGE_RAIL_DEFAULT_WIDTH/, 'page rail should track mutable width state');
assert.match(html, /let projectPageRailCollapsed = false/, 'page rail should track collapsed state');
assert.match(html, /let isResizingProjectPageRail = false/, 'page rail resize should have explicit pointer state');
assert.match(html, /function loadProjectPageRailLayout/, 'page rail layout should restore persisted settings');
assert.match(html, /function saveProjectPageRailLayout/, 'page rail layout should persist after resize or collapse');
assert.match(html, /function applyProjectPageRailLayout/, 'page rail layout should apply width and hidden state centrally');
assert.match(html, /function startProjectPageRailResize/, 'page rail resize should start from the drag handle');
assert.match(html, /function resizeProjectPageRailFromPointer/, 'page rail resize should update width from pointer movement');
assert.match(html, /function finishProjectPageRailResize/, 'page rail resize should finish cleanly and persist');
assert.match(html, /function setProjectPageRailCollapsed/, 'page rail collapse and expand should share one state setter');
assert.match(html, /projectPageRailResizeHandle\.addEventListener\('pointerdown', startProjectPageRailResize\)/, 'resize handle should be wired');
assert.match(html, /collapseProjectPageRailBtn\.addEventListener\('click'[\s\S]*?setProjectPageRailCollapsed\(true\)/, 'collapse button should hide the page rail');
assert.match(html, /expandProjectPageRailBtn\.addEventListener\('click'[\s\S]*?setProjectPageRailCollapsed\(false\)/, 'restore tab should expand the page rail');
assert.match(html, /let projectPages = \[\]/, 'active project should keep pages in a single pages array');
assert.match(html, /let currentPageId = null/, 'active project should track the current page id');
assert.match(html, /let selectedPageIds = \[\]/, 'page rail should support multi-selection state');
assert.match(html, /let copiedPages = \[\]/, 'page copy and paste should use an internal page clipboard');
assert.match(html, /function createEditorPageSnapshot/, 'current canvas state should serialize into a project page snapshot');
assert.match(html, /function applyEditorPageSnapshot/, 'project pages should restore into the existing editor state');
assert.match(html, /function syncCurrentPageSnapshot/, 'page switches should save the current page before leaving it');
assert.match(html, /function renderProjectPageRail/, 'page rail should render page thumbnails and selection state');
assert.match(html, /function selectProjectPage/, 'page clicks should switch the active editor page');
assert.match(html, /function createBlankProjectPage/, 'new pages should start as empty drop targets');
assert.match(html, /function duplicateSelectedPages/, 'selected pages should be duplicable like presentation slides');
assert.match(html, /function deleteSelectedPages/, 'selected pages should be deletable as a group');
assert.match(html, /function copySelectedPages/, 'selected pages should be copyable');
assert.match(html, /function pasteCopiedPages/, 'copied pages should be pasteable');
assert.match(extractFunctionBody('createSerializableProject'), /pages: projectPages\.map/, 'project export should persist all pages, not only the current canvas');
assert.match(extractFunctionBody('applySerializableProject'), /project\.pages/, 'project import should read multi-page project data');
assert.match(extractFunctionBody('applySerializableProject'), /migrateSinglePageProject/, 'project import should migrate older single-page JSON');
assert.match(html, /saveProjectBtn\.addEventListener\('click', deferredManualProjectDownload\)/, 'project save button should export the active project JSON');
assert.match(html, /loadProjectInput\.addEventListener\('change', handleProjectImport\)/, 'project load input should import active project JSON');
assert.match(html, /addProjectPageBtn\.addEventListener\('click', addProjectPage\)/, 'new-page button should create a project page');
assert.match(html, /duplicateProjectPageBtn\.addEventListener\('click', duplicateSelectedPages\)/, 'duplicate-page button should duplicate selected pages');
assert.match(html, /deleteProjectPageBtn\.addEventListener\('click', deleteSelectedPages\)/, 'delete-page button should delete selected pages');
assert.match(html, /e\.key\.toLowerCase\(\) === 'c'[\s\S]*?copySelectedPages/, 'Ctrl+C should copy selected pages when component copy does not run');
assert.match(html, /e\.key\.toLowerCase\(\) === 'v'[\s\S]*?pasteCopiedPages/, 'Ctrl+V should paste copied pages when component paste does not run');
assert.match(html, /e\.key\.toLowerCase\(\) === 'd'[\s\S]*?duplicateSelectedPages/, 'Ctrl+D should duplicate selected pages when component duplicate does not run');

assert.doesNotMatch(html, /id="canvasExtendPanel"/, 'outside-image annotations should expand the canvas automatically instead of exposing manual controls');
assert.doesNotMatch(html, /canvas-extend-btn/, 'manual canvas extension buttons should be removed from the editing sidebar');
assert.doesNotMatch(html, /fitImageFrameBtn|resetCanvasToImageFrame/, 'manual canvas fitting controls should be removed with the manual extension workflow');
assert.match(html, /let imageFrame = \{ x: 0, y: 0, w: 0, h: 0 \}/, 'original image bounds should be tracked separately from output canvas bounds');
assert.match(html, /const AUTO_CANVAS_MARGIN = calculateScaledSize\(48\)/, 'auto canvas expansion should leave a small working margin around outside annotations');
assert.match(html, /function getCanvasOverflowForBounds/, 'canvas overflow should be calculated from object bounds');
assert.match(html, /function autoExpandCanvasForBounds/, 'canvas extension should be automatic when objects cross the current canvas bounds');
assert.match(html, /function applyCanvasExpansionToInteractionAnchors/, 'left and top canvas growth should keep active drag anchors visually stable');
assert.match(html, /dragStartX \+= expansion\.left/, 'drag origin should be shifted when canvas expands to the left');
assert.match(html, /focusStartX \+= expansion\.left/, 'focus creation origin should be shifted when canvas expands to the left');
assert.match(html, /viewportPanX -= expansion\.left \* viewportScale/, 'left-side auto expansion should preserve the apparent canvas position in the viewport');
assert.match(html, /ctx\.drawImage\(bgImage, imageFrame\.x, imageFrame\.y, imageFrame\.w, imageFrame\.h\)/, 'background image should render inside its frame instead of stretching to the whole output canvas');
assert.match(html, /function normalizeCanvasAnchoredPosition/, 'normalized badge and text positions should survive canvas expansion');
assert.match(html, /autoExpandCanvasForBounds\(getBoundsForItems\(selection\)\)/, 'dragging a selection past the canvas edge should grow the workspace automatically');
assert.match(html, /autoExpandCanvasForBounds\(getItemBounds\(selectedFocusArea\)\)/, 'drawing or resizing focus shapes past the edge should grow the workspace automatically');
assert.match(html, /autoExpandCanvasForBounds\(getBadgeBounds\(placingBadge\)\)/, 'drag-sizing a badge past the edge should grow the workspace automatically');
assert.match(html, /function drawImageFrameGuide/, 'original image boundary should remain visible while editing an expanded canvas');
assert.match(html, /function createSnapGuideLabel/, 'snap guides should explain what target was used');
assert.match(html, /function drawSnapGuideLabels/, 'snap guide labels should be rendered on the canvas');
assert.match(html, /image-left/, 'snap targets should include original image boundaries');
assert.match(html, /function selectToolByShortcut/, 'editor modes should have keyboard shortcuts');
assert.match(html, /case 'v': return selectTool\('select'\)/, 'V shortcut should switch to select mode');
assert.match(html, /case 'r': return selectTool\('focus-rect'\)/, 'R shortcut should switch to rectangle focus mode');
assert.match(html, /case 'b': return selectTool\('badge'\)/, 'B shortcut should switch to badge mode');
assert.match(html, /id="toolRedact"/, 'manual workflow should include a sensitive-information redaction tool');
assert.doesNotMatch(html, /function applyRedactionToImage/, 'redaction should stay editable instead of destructively rewriting the working image');
assert.match(html, /redact: \{ mosaicSize: \d+ \}/, 'redaction tool should have a mosaic-size default');
assert.match(html, /id="redactionStylePanel"[^>]*hidden/, 'redaction controls should live in their own tool or selection panel');
assert.match(html, /id="redactionMosaicRange"/, 'redaction controls should expose mosaic resolution');
assert.match(html, /function getRedactionMosaicSize/, 'redaction mosaic resolution should be normalized centrally');
assert.match(html, /function getRedactionBounds/, 'redaction objects should expose bounds like focus objects');
assert.match(html, /function drawMosaicRedaction/, 'redaction should render as a mosaic overlay');
assert.match(html, /function updateRedactionStylePanel/, 'redaction mosaic panel should update by tool and selection');
assert.match(html, /function applyRedactionMosaicSize/, 'redaction mosaic resolution should apply through a style controller');
assert.match(extractFunctionBody('isElementObject'), /'redact'/, 'redaction should participate in shared element selection');
assert.match(extractFunctionBody('getItemBounds'), /item\.type === 'redact'/, 'redaction should participate in shared bounds calculations');
assert.match(extractFunctionBody('hitElementObject'), /el\.type === 'redact'/, 'redaction should be selectable from the canvas');
assert.match(extractFunctionBody('executeDeleteSelected'), /'redact'/, 'selected redactions should delete through the shared delete command');
assert.match(extractFunctionBody('shiftPixelAnchoredObject'), /item\.type === 'rect' \|\| item\.type === 'circle' \|\| item\.type === 'redact'/, 'redactions should shift when automatic canvas expansion adds left or top space');
assert.match(html, /Object\.assign\(toolDefaults\.redact, project\.toolDefaults\?\.redact \|\| \{\}\)/, 'project import should restore or default redaction mosaic settings');
assert.match(html, /redactionMosaicRange\.addEventListener\('input'[\s\S]*?applyRedactionMosaicSize\(redactionMosaicRange\.value\)/, 'redaction mosaic slider should apply immediately');
assert.match(extractFunctionBody('updateSelectedActionArea'), /updateRedactionStylePanel\(\)/, 'selecting a redaction should refresh the mosaic controls');
assert.match(html, /let isResizingRedaction = false/, 'redaction resize should have explicit interaction state');
assert.match(html, /function getRedactionHandleAt/, 'selected redactions should expose resize handles');
assert.match(html, /function resizeRedactionFromPoint/, 'selected redactions should resize through the same pointer flow as focus rectangles');
assert.match(html, /if \(selectedElement && selectedElement\.type === 'redact'\) \{[\s\S]*?getRedactionHandleAt/, 'selected redaction handles should work before creation-mode branching');
assert.match(html, /if \(isResizingRedaction && selectedElement && selectedElement\.type === 'redact'\)/, 'mouse move should resize the active redaction object');
assert.match(html, /type: 'redact'[\s\S]*?mosaicSize: toolDefaults\.redact\.mosaicSize[\s\S]*?addEditorObject\(newRedaction\)[\s\S]*?selectedElement = newRedaction/, 'new redactions should be created as selected editable elements');
assert.match(html, /if \(isDrawingRedaction && redactionArea\) \{[\s\S]*?saveHistoryState\(\)/, 'finished redactions should save the selected object into undo history');

assert.match(html, /function toggleCanvasSelectionItem/, 'canvas should support additive selection toggling like presentation editors');
assert.match(html, /if \(e\.shiftKey && clicked\) \{[\s\S]*?toggleCanvasSelectionItem\(clicked\)/, 'shift-clicking an object should add or remove it from the current selection');
assert.match(html, /function selectAllEditableObjects/, 'editor should support Ctrl+A select all for editable objects');
assert.match(extractFunctionBody('selectAllEditableObjects'), /filter\(item => isObjectVisible\(item\) && !isObjectLocked\(item\)\)/, 'Ctrl+A should select only unlocked editable objects');
assert.match(html, /function duplicateSelectedComponents/, 'editor should support direct duplicate command without using the clipboard');
assert.match(html, /e\.key\.toLowerCase\(\) === 'd'[\s\S]*?duplicateSelectedComponents\(\)/, 'Ctrl+D should duplicate selected components');
assert.match(html, /e\.key\.toLowerCase\(\) === 'a'[\s\S]*?selectAllEditableObjects\(\)/, 'Ctrl+A should select all editable components');
assert.match(html, /function getMultiSelectionBounds/, 'multi-selection should expose a group bounds model');
assert.match(html, /function drawMultiSelectionBounds/, 'multi-selection should render a group bounding box');
assert.match(html, /drawMultiSelectionBounds\(\)/, 'canvas rendering should draw a group outline for multi-selection');
assert.match(html, /function getLinePointHandleAt/, 'selected lines should expose editable point handles');
assert.match(html, /let isEditingLinePoint = false/, 'line point edits should have explicit interaction state');
assert.match(html, /isEditingLinePoint && selectedElement && selectedElement\.type === 'line'/, 'mouse move should update the active line point while editing');
assert.match(html, /function getRotationHandleAt/, 'selected objects should expose a rotation handle');
assert.match(html, /function rotateSelectionFromPointer/, 'dragging the rotation handle should rotate the selection');
assert.match(html, /let isRotatingSelection = false/, 'rotation should have explicit interaction state');
assert.match(html, /function drawRotationHandle/, 'selected objects should draw a visible rotation handle');
assert.match(html, /function startSelectedObjectInteraction\(pos, e\)/, 'selected object handles should be processed independently from the active tool');
assert.match(html, /dragStartX = pos\.x; dragStartY = pos\.y;[\s\S]*?if \(startSelectedObjectInteraction\(pos, e\)\) return;[\s\S]*?if \(currentTool === 'select'\)/, 'selected object handles should run before creation or select-mode branching');
assert.doesNotMatch(extractFunctionBody('updateSelectedTextEditArea'), /currentTool\s*!==\s*'select'/, 'selected badge and text editing should be visible even while a creation tool remains active');
assert.match(extractFunctionBody('updateSelectedActionArea'), /if \(count > 0\)/, 'selected action buttons should show whenever components are selected');
assert.doesNotMatch(extractFunctionBody('updateSelectedActionArea'), /currentTool\s*===\s*'select'\s*&&\s*count > 0/, 'selected action buttons should not depend on select mode');
assert.match(html, /function updateBadgePlacementFromDrag/, 'badge placement should support press-drag sizing');
assert.match(html, /let badgePlacementStart = null/, 'badge placement should remember the drag origin');
assert.match(html, /updateBadgePlacementFromDrag\(placingBadge, badgePlacementStart, pos\)/, 'badge placement mouse move should size from the drag gesture');
assert.match(html, /updateBadgePlacementFromDrag\(placingBadge, badgePlacementStart, pos\);[\s\S]*?activeSnapGuides = \[\];[\s\S]*?autoExpandCanvasForBounds\(getBadgeBounds\(placingBadge\)\)/, 'drag-sizing a new badge should clear snap guides before canvas expansion');
assert.match(html, /reindexBadges\(\);[\s\S]*?activeSnapGuides = \[\];[\s\S]*?autoExpandCanvasForBounds\(getBadgeBounds\(newBadge\)\)/, 'initial badge creation should start without snap guides');
assert.doesNotMatch(extractFunctionBody('setBadgeCenterFromPoint'), /clampNumber/, 'badge drag placement should not clamp before auto canvas expansion can run');
assert.match(extractFunctionBody('applySnapToBadgeResize'), /clampNumber\(snappedRadius \/ calculateScaledSize\(BADGE_BASE_RADIUS\), BADGE_MIN_SCALE, BADGE_MAX_SCALE\)/, 'completed badge resize should still support snapped radius sizing');

console.log('manual-tool custom color checks passed');
