import fs from 'node:fs';
import assert from 'node:assert/strict';

const html = fs.readFileSync(new URL('../manual-tool/index.html', import.meta.url), 'utf8');

assert.match(html, /id="addCustomColorBtn"/, 'custom color add button should exist');
assert.match(html, /id="customColorModal"/, 'custom color modal should exist');
assert.match(html, /id="customColorInput"/, 'color input should exist');
assert.match(html, /id="customColorHexInput"/, 'hex input should exist');
assert.match(html, /manualToolCustomColors/, 'custom colors should be persisted in localStorage');
assert.match(html, /function normalizeHexColor/, 'hex colors should be normalized before use');
assert.match(html, /function renderCustomColorButtons/, 'saved custom colors should render into the palette');
assert.match(html, /function selectColorButton/, 'dynamic color buttons should share the existing selection behavior');
assert.match(html, /function calculateFittedCanvasSize/, 'canvas fit size should be reusable after viewport changes');
assert.match(html, /function resizeCanvasToViewport/, 'canvas should resize when the viewport grows or shrinks');
assert.match(html, /window\.addEventListener\('resize', handleWindowResize\)/, 'window resize should trigger canvas refit');
assert.match(html, /imageAutoFitEnabled = false/, 'manual background resizing should disable automatic viewport fitting');
assert.match(html, /const CREATION_TOOLS = \['focus-rect', 'focus-circle', 'badge'\]/, 'creation tools should stay active for repeated placement');
assert.match(html, /if \(CREATION_TOOLS\.includes\(currentTool\)\) {\s*selectedFocusArea = null;\s*} else {[\s\S]*?selectTool\('select'\)/, 'created focus shapes should not force creation tools back to select mode');
assert.match(html, /let copiedComponents = \[\]/, 'selected components should have an internal clipboard');
assert.match(html, /function copySelectedComponents/, 'selected components should be copyable');
assert.match(html, /function pasteCopiedComponents/, 'copied components should be pasteable');
assert.match(html, /saveHistoryState\(\); drawCanvas\(\); updateSelectedActionArea\(\);[\s\S]*?붙여넣었습니다/, 'pasted components should be saved into undo history');
assert.match(html, /e\.key\.toLowerCase\(\) === 'c'[\s\S]*?copySelectedComponents/, 'Ctrl+C should copy selected components');
assert.match(html, /e\.key\.toLowerCase\(\) === 'v'[\s\S]*?pasteCopiedComponents/, 'Ctrl+V should paste copied components before image paste handling');
assert.match(html, /function isNearHandle/, 'resize hit testing should target handles, not the whole border');
const focusHandleBody = html.match(/function getFocusHandleAt\(pos, f\) \{([\s\S]*?)\n    function getCropHandleAt/);
assert.ok(focusHandleBody, 'focus handle hit testing should be inspectable');
assert.doesNotMatch(focusHandleBody[1], /Math\.abs\(pos\.y - f\.y\) < size && inX/, 'top focus border should not all become a resize handle');
assert.doesNotMatch(focusHandleBody[1], /Math\.abs\(pos\.x - f\.x\) < size && inY/, 'left focus border should not all become a resize handle');
assert.match(html, /id="badgeTypePanel"[^>]*hidden/, 'badge type options should be hidden initially');
assert.match(html, /function updateToolSpecificPanels/, 'tool-specific option panels should be updated on tool changes');
assert.match(html, /badgeTypePanel\.classList\.toggle\('hidden', currentTool !== 'badge'\)/, 'badge type options should only show in badge mode');
assert.match(html, /id="selectedTextEditArea"/, 'selected badge and text elements should expose a text edit area');
assert.match(html, /id="selectedTextColorInput"/, 'selected badge and text elements should expose text color editing');
assert.doesNotMatch(html, /id="selectedTextColorInput"[^>]*type="color"/, 'selected text color editing should not use the native color picker');
assert.match(html, /id="selectedTextColorPalette"/, 'selected text color editing should use an in-panel palette');
assert.match(html, /function toggleSelectedTextColorPalette/, 'selected text color palette should be toggled inside the app');
assert.match(html, /function setSelectedTextColorDraft/, 'selected text color palette should update the draft color without closing');
assert.match(html, /function applySelectedTextColor/, 'selected text color palette should immediately apply color to the selected element');
assert.match(html, /applySelectedTextColor\(btn\.getAttribute\('data-color'\)\)/, 'clicking a text color option should update the selected element immediately');
assert.match(html, /const toolDefaults = \{/, 'editor styles should have tool-level defaults');
assert.match(html, /badge: \{ fillColor: '#FF4747', textColor: '#FFFFFF', badgeStyle: 'number', badgeScale: 1 \}/, 'badge tool should keep fill, text color, label, and size defaults');
assert.match(html, /id="textStylePanel"/, 'text style controls should live in a tool/selection style panel');
assert.match(html, /toolDefaults\.badge\.textColor = normalized/, 'badge mode color changes should update future badge defaults');
assert.match(html, /textColor: toolDefaults\.badge\.textColor/, 'new badges should copy the badge tool text color');
assert.match(html, /textColor: toolDefaults\.text\.textColor/, 'new text bubbles should copy the text tool text color');
assert.doesNotMatch(html, /테두리 & 뱃지 색상/, 'generic color panel label should be removed');
assert.match(html, /id="objectStylePanel"[^>]*hidden/, 'fill and stroke colors should live in a mode-specific style panel');
assert.match(html, /id="objectStylePanelTitle"/, 'mode-specific style panel should have a dynamic title');
assert.match(html, /id="objectColorSwatch"/, 'object color panel should use the same swatch control as text color');
assert.match(html, /id="objectColorInput"[^>]*class="w-20 min-w-0/, 'object color hex input should match text color input sizing');
assert.match(html, /id="colorPalette" class="grid grid-cols-6 gap-1.5"/, 'object color palette should use the same grid layout as text color');
assert.match(html, /class="color-picker-btn w-6 h-6 rounded-full border border-slate-200 bg-\[#FFFFFF\]" data-color="#FFFFFF"/, 'object color palette should include the same white swatch as text color');
assert.doesNotMatch(html, /color-picker-btn[^"]*w-7 h-7/, 'object custom color swatches should use the same size as text color swatches');
assert.doesNotMatch(html, /class="color-picker-btn[^"]*ring-\[/, 'object color swatches should not use a different selected-state UI from text color swatches');
assert.match(html, /function updateObjectStylePanel/, 'object style panel should update by current tool and selection');
assert.match(html, /function applyObjectFillColor/, 'fill and stroke color choices should apply through the style controller');
assert.match(html, /toolDefaults\.badge\.fillColor = normalized/, 'badge mode fill color changes should update future badge defaults');
assert.match(html, /color: toolDefaults\.badge\.fillColor/, 'new badges should copy the badge tool fill color');
assert.match(html, /function getSingleEditableTextElement/, 'text editing should target one selected badge or text element');
assert.match(html, /function applySelectedTextEdit/, 'selected text edits should be applied explicitly');
assert.match(html, /el\.textColor \|\| '#ffffff'/, 'badge and text drawing should support per-element text colors');
assert.match(html, /if \(el\.manualText\) return;/, 'manually edited badge labels should not be overwritten by reindexing');
assert.match(html, /let viewportScale = 1/, 'workspace should track a separate viewport zoom scale');
assert.match(html, /function applyViewportTransform/, 'viewport transform should be centralized');
assert.match(html, /function zoomViewportAt/, 'wheel zoom should preserve the pointer anchor');
assert.match(html, /id="resetViewportBtn"/, 'viewport navigation should expose a reset-to-origin button');
assert.match(html, /id="viewportZoomToolbar"/, 'viewport navigation controls should be grouped in a toolbar');
assert.match(html, /id="zoomOutBtn"/, 'viewport toolbar should expose zoom out');
assert.match(html, /id="zoomInBtn"/, 'viewport toolbar should expose zoom in');
assert.match(html, /id="fitViewportBtn"/, 'viewport toolbar should expose fit-to-screen');
assert.doesNotMatch(html, /id="actualSizeViewportBtn"/, 'viewport toolbar should not expose a duplicate actual-size view');
assert.match(html, /id="zoomPercentLabel"/, 'viewport toolbar should show the current zoom percent');
assert.match(html, /const resetViewportBtn = document\.getElementById\('resetViewportBtn'\)/, 'reset viewport button should be bound');
assert.match(html, /const zoomOutBtn = document\.getElementById\('zoomOutBtn'\)/, 'zoom out button should be bound');
assert.match(html, /const zoomInBtn = document\.getElementById\('zoomInBtn'\)/, 'zoom in button should be bound');
assert.match(html, /const fitViewportBtn = document\.getElementById\('fitViewportBtn'\)/, 'fit viewport button should be bound');
assert.doesNotMatch(html, /actualSizeViewportBtn/, 'actual-size button wiring should be removed');
assert.match(html, /const zoomPercentLabel = document\.getElementById\('zoomPercentLabel'\)/, 'zoom percent label should be bound');
assert.match(html, /function handleViewportWheel/, 'workspace wheel events should drive viewport zoom');
assert.match(html, /function shouldHandleViewportWheel/, 'wheel zoom should be filtered before changing zoom');
assert.match(html, /function handleViewportPanStart/, 'right-button drag should start viewport panning');
assert.match(html, /function handleViewportPanMove/, 'right-button drag should move the viewport');
assert.match(html, /function finishViewportPan/, 'right-button drag should end viewport panning cleanly');
assert.match(html, /function updateViewportZoomLabel/, 'viewport zoom percent should update after zoom changes');
assert.match(html, /function zoomViewportByStep/, 'viewport toolbar should reuse step zoom behavior');
assert.match(html, /function setViewportScaleAtCenter/, 'toolbar zoom should anchor at the workspace center');
assert.match(html, /function fitViewportToWorkspace/, 'viewport should support fitting the whole canvas into the workspace');
assert.match(html, /function updateViewportResetButton/, 'reset-to-origin button visibility should follow image state');
assert.match(html, /function updateViewportToolbar/, 'viewport toolbar visibility and disabled state should be centralized');
assert.match(html, /zoomOutBtn\.addEventListener\('click'[\s\S]*?zoomViewportByStep\(1\)/, 'zoom out button should zoom out one step');
assert.match(html, /zoomInBtn\.addEventListener\('click'[\s\S]*?zoomViewportByStep\(-1\)/, 'zoom in button should zoom in one step');
assert.match(html, /fitViewportBtn\.addEventListener\('click', fitViewportToWorkspace\)/, 'fit button should fit the canvas to the workspace');
assert.match(html, /resetViewportBtn\.addEventListener\('click', resetViewportTransform\)/, 'reset-to-origin button should reset viewport transform');
assert.match(html, /e\.key === '0'[\s\S]*?resetViewportTransform\(\)/, 'Ctrl+0 should reset viewport transform');
assert.match(html, /e\.key === '=' \|\| e\.key === '\+'/, 'Ctrl+plus should zoom in');
assert.match(html, /e\.key === '-'[\s\S]*?zoomViewportByStep\(1\)/, 'Ctrl+minus should zoom out');
assert.match(html, /let isSpacePanActive = false/, 'space-drag panning should track spacebar state');
assert.match(html, /e\.button === 1 \|\| \(e\.button === 0 && isSpacePanActive\)/, 'viewport panning should also support middle drag and space-left drag');
assert.match(html, /e\.code === 'Space'[\s\S]*?isSpacePanActive = true/, 'holding Space should enable panning');
assert.match(html, /window\.addEventListener\('keyup'[\s\S]*?isSpacePanActive = false/, 'releasing Space should stop space-pan mode');
assert.match(html, /canvasContainer\.addEventListener\('wheel', handleViewportWheel, \{ passive: false \}\)/, 'wheel zoom should be scoped to the canvas instead of the whole workspace');
assert.doesNotMatch(html, /workspace\.addEventListener\('wheel', handleViewportWheel/, 'workspace-level wheel zoom should not accidentally catch unrelated scroll events');
assert.match(html, /const VIEWPORT_WHEEL_AFTER_PAN_IGNORE_MS = \d+/, 'stray wheel events immediately after panning should be ignored');
assert.match(html, /Date\.now\(\) - lastViewportPanEndedAt < VIEWPORT_WHEEL_AFTER_PAN_IGNORE_MS/, 'wheel zoom should ignore residual wheel events right after panning');
assert.match(html, /Math\.abs\(e\.deltaY\) < 1/, 'wheel zoom should ignore zero vertical wheel delta');
assert.match(html, /Math\.abs\(e\.deltaX\) > Math\.abs\(e\.deltaY\)/, 'horizontal wheel gestures should not be treated as zoom');
assert.match(html, /if \(!shouldHandleViewportWheel\(e\)\) return;/, 'wheel handler should return before preventing default when a wheel is unrelated to zooming');
assert.match(html, /function shouldSuppressHorizontalViewportWheel/, 'horizontal wheel suppression should be centralized');
assert.match(html, /Math\.abs\(e\.deltaX\) >= 1/, 'horizontal wheel suppression should detect real horizontal deltas');
assert.match(html, /Math\.abs\(e\.deltaX\) >= Math\.abs\(e\.deltaY\)/, 'horizontal wheel suppression should ignore diagonal vertical zoom gestures');
assert.match(html, /function suppressHorizontalViewportWheel/, 'workspace horizontal wheel events should have a suppress-only handler');
assert.match(html, /workspace\.addEventListener\('wheel', suppressHorizontalViewportWheel, \{ passive: false, capture: true \}\)/, 'horizontal wheel suppression should run before workspace scrolling');
assert.match(html, /if \(shouldSuppressHorizontalViewportWheel\(e\)\) \{[\s\S]*?e\.preventDefault\(\);[\s\S]*?e\.stopPropagation\(\);[\s\S]*?return;[\s\S]*?\}/, 'canvas wheel handler should block horizontal wheel default scrolling without zooming');
assert.match(html, /if \(!shouldSuppressHorizontalViewportWheel\(e\)\) return;[\s\S]*?e\.preventDefault\(\);[\s\S]*?e\.stopPropagation\(\);/, 'workspace suppress handler should prevent and stop horizontal wheel events');
assert.match(html, /workspace\.addEventListener\('pointerdown', handleViewportPanStart, true\)/, 'right-click panning should use pointer events before canvas editing handlers');
assert.match(html, /document\.addEventListener\('contextmenu', suppressViewportContextMenu, true\)/, 'context menu should be suppressed at capture phase while viewport panning is available');
assert.match(html, /workspace\.contains\(e\.target\)/, 'context menu suppression should stay scoped to the editing workspace');
assert.match(html, /window\.addEventListener\('pointermove', handleViewportPanMove\)/, 'panning should continue if the pointer leaves the canvas');
assert.match(html, /window\.addEventListener\('pointerup', finishViewportPan\)/, 'panning should stop on global pointerup');
assert.match(html, /window\.addEventListener\('pointercancel', finishViewportPan\)/, 'panning should stop on pointer cancellation');
assert.match(html, /window\.addEventListener\('blur', finishViewportPan\)/, 'panning should stop when the browser window loses focus');
assert.match(html, /workspace\.setPointerCapture\(e\.pointerId\)/, 'viewport panning should capture the active pointer');
assert.match(html, /workspace\.releasePointerCapture\(panPointerId\)/, 'viewport panning should release pointer capture when done');
assert.match(html, /if \(isPanningViewport\) \{ finishViewportPan\(\); return; \}/, 'wheel zoom should clear stale pan state and ignore that wheel event');
assert.match(html, /if \(e\.buttons === 0\) \{ finishViewportPan\(e\); return; \}/, 'pointermove should clear stale pan state if no button is pressed');
assert.match(html, /canvas\.addEventListener\('mousedown'[\s\S]*?if \(e\.button !== 0 \|\| isSpacePanActive\) return;/, 'canvas editing should ignore right, middle, and space-pan mouse actions');
const viewportWheelBody = html.match(/function shouldHandleViewportWheel\(e\) \{([\s\S]*?)\n    function handleViewportWheel/);
assert.ok(viewportWheelBody, 'wheel zoom guard should be inspectable');
assert.doesNotMatch(viewportWheelBody[1], /currentTool/, 'wheel zoom should not be limited to a specific editing mode');
const viewportPanBody = html.match(/function handleViewportPanStart\(e\) \{([\s\S]*?)\n    function handleViewportPanMove/);
assert.ok(viewportPanBody, 'viewport pan start guard should be inspectable');
assert.doesNotMatch(viewportPanBody[1], /currentTool/, 'viewport panning should not be limited to a specific editing mode');
assert.match(html, /if \(!bgImage \|\| canvasContainer\.classList\.contains\('hidden'\)\) return false;/, 'wheel zoom should work in every editing mode when an image is loaded');
assert.match(html, /if \(e\.code === 'Space' && bgImage\)/, 'space panning should work in every editing mode');
assert.match(html, /if \(!shouldPan \|\| !bgImage \|\| canvasContainer\.classList\.contains\('hidden'\)\) return;/, 'right and middle panning should work in every editing mode');
assert.match(html, /if \(bgImage && isViewportContext\)/, 'viewport context menu suppression should not depend on select mode');
assert.match(html, /\(e\.clientX - bgInitialClientX\) \/ viewportScale/, 'background resize drag distance should stay correct while the viewport is zoomed');
assert.match(html, /const BADGE_BASE_RADIUS = 14/, 'badge drawing should have a reusable base radius');
assert.match(html, /const BADGE_MIN_SCALE = 0\.6/, 'badge resizing should have a minimum scale');
assert.match(html, /const BADGE_MAX_SCALE = 3/, 'badge resizing should have a maximum scale');
assert.match(html, /function getBadgeScale/, 'badge elements should normalize their scale');
assert.match(html, /function getBadgeRadius/, 'badge drawing should use a reusable scaled radius');
assert.match(html, /function getBadgeBounds/, 'badge selection should expose bounds for handles and snapping');
assert.match(html, /function getBadgeHandleAt/, 'selected badges should expose resize handles');
assert.match(html, /function resizeBadgeFromPoint/, 'badge resizing should be pointer driven');
assert.match(html, /let isPlacingBadge = false/, 'badge placement should track mouse-down drag placement');
assert.match(html, /let placingBadge = null/, 'badge placement should keep the pending badge until mouseup');
assert.match(html, /isPlacingBadge = true/, 'badge mousedown should start placement instead of saving immediately');
assert.match(html, /if \(isPlacingBadge && placingBadge\)/, 'badge mousemove should update the pending badge');
assert.match(html, /function finishBadgePlacement/, 'badge placement should finalize through a reusable mouseup handler');
assert.match(html, /window\.addEventListener\('mouseup', \(\) => \{ finishBadgePlacement\(\); \}\)/, 'badge placement should finalize even if the pointer leaves the canvas');
assert.match(html, /scale: toolDefaults\.badge\.badgeScale/, 'new badges should copy the tool-level size default');
assert.match(html, /let isResizingBadge = false/, 'badge resizing should have explicit interaction state');
assert.match(html, /if \(selectedElement && selectedElement\.type === 'badge'\)/, 'badge resize handles should be checked before dragging selection');
assert.match(html, /if \(isResizingBadge && selectedElement && selectedElement\.type === 'badge'\)/, 'badge mousemove should resize the selected badge');
assert.match(html, /function getItemBounds/, 'snap logic should use shared item bounds');
assert.match(html, /function getBoundsForItems/, 'snap logic should support moving grouped selections');
assert.match(html, /function getSnapAnchors/, 'snap logic should compare edges, centers, and corners');
assert.match(html, /function getSnapTargets/, 'snap logic should collect canvas and component targets');
assert.match(html, /function snapBoundsToTargets/, 'moving and placing should adjust to nearby snap targets');
assert.match(html, /function drawSnapGuides/, 'snap alignments should be visible while editing');
assert.match(html, /activeSnapGuides = snapResult\.guides/, 'active snap guides should be updated from snap results');
assert.match(html, /const SNAP_THRESHOLD_PX = 8/, 'snap threshold should be defined in screen pixels');
assert.match(html, /canvas\.width \/ rect\.width/, 'snap threshold should account for viewport zoom');
assert.match(html, /item\.type === 'line'[\s\S]*?item\.points\.forEach/, 'line endpoints should contribute snap anchors');
assert.match(html, /function shouldBypassSnap\(e\)/, 'snap bypass should be centralized');
assert.match(html, /return e\?\.shiftKey === true/, 'holding Shift should bypass snap behavior');
assert.match(html, /function applySnapUnlessBypassed\(e, snapAction\)/, 'snap application and Shift bypass should share one helper');
assert.match(html, /if \(shouldBypassSnap\(e\)\) \{[\s\S]*?activeSnapGuides = \[\];[\s\S]*?return false;[\s\S]*?\}/, 'snap bypass helper should clear guides and report that snapping was skipped');
assert.match(html, /applySnapUnlessBypassed\(e, \(\) => applySnapToBadgePlacement\(newBadge\)\)/, 'holding Shift should disable initial badge placement snap on mousedown');
assert.match(html, /applySnapUnlessBypassed\(e, \(\) => applySnapToBadgePlacement\(placingBadge\)\)/, 'holding Shift should disable snap while placing badges');
assert.match(html, /applySnapUnlessBypassed\(e, \(\) => applySnapToBadgeResize\(selectedElement\)\)/, 'holding Shift should disable snap while resizing badges');
assert.match(html, /const snappedDelta = shouldBypassSnap\(e\) \? \{ dx, dy \} : getSnappedMoveDelta\(selection, dx, dy\)/, 'holding Shift should disable snap while moving selected components');
assert.match(html, /if \(shouldBypassSnap\(e\)\) activeSnapGuides = \[\];/, 'holding Shift should clear visible snap guides during movement');
assert.match(html, /points\[points\.length - 1\] = shouldBypassSnap\(e\) \? orthogonalPos : snapPointToTargets\(orthogonalPos, \[drawingLineInstance\]\)/, 'holding Shift should disable snap while moving line endpoints');
assert.match(html, /function snapFocusDraftToTargets\(focus, e\)/, 'focus draft snapping should receive the pointer event');
assert.match(html, /if \(shouldBypassSnap\(e\)\) \{[\s\S]*?activeSnapGuides = \[\];[\s\S]*?return;[\s\S]*?\}/, 'holding Shift should disable snap while drawing focus rectangles');
assert.match(html, /if \(e\.key === 'Shift' && activeSnapGuides\.length\)/, 'pressing Shift should immediately clear visible snap guides');

console.log('manual-tool custom color checks passed');
